# site properties and page defaults
title: Aimee Schulz
subtitle: PhD Candidate in Plant Breeding and Genetics
description: NSF Graduate Research Fellow at Cornell University
header: images/FieldSunny.jpg
footer: images/FieldSunny.jpg
proofer: false

# site social media and other links
links:
  email: ajs692@cornell.edu
  orcid: 0000-0002-3709-9898
  google-scholar: v2u2ywYAAAAJ
  twitter: aimeejschulz

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
    # change to true when actually changing
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
